### PR TITLE
fix(buffer): check for errors using errors.Is() incase of wrapping

### PR DESCRIPTION
**Pull request by halkyon**
This change is [Reviewable](https://reviewable.io/reviews/outcaste-io/ristretto/1)

### CODE REVIEW

**Review by manishrjain — APPROVED** [review]
:lgtm: Thanks for the PR!

> *[Reviewable](https://reviewable.io/reviews/outcaste-io/ristretto/1#-:-MyIQDJy2bW9luti0fW7:bke5l8x)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by manishrjain** [comment]
@halkyon -- Typically, I'd merge this, but then GitHub ends up creating two commits. So, was wondering -- Does GitHub show you an option to merge this yourself?

**Comment by halkyon** [comment]
@manishrjain unfortunately I don't see any option, it looks like the "code-review/reviewable" check is still pending so it's not available.

**Comment by manishrjain** [comment]
Done. Thanks again!

**Pull request merged**
